force-app/main/default/objects/Twitter_Setting__mdt/Twitter_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Twitter Setting</label>
    <pluralLabel>Twitter Setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/Twitter_Setting__mdt/fields/Access_Token_Secret__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Secret__c</fullName>
    <label>Access Token Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twitter_Setting__mdt/fields/Base_API_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_API_URL__c</fullName>
    <label>Base API URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Twitter_Setting__mdt/fields/Code_Challenge__c.field-meta.xml
<CustomField>
    <fullName>Code_Challenge__c</fullName>
    <label>Code Challenge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twitter_Setting__mdt/fields/Consumer_Secret__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Secret__c</fullName>
    <label>Consumer Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twitter_Setting__mdt/fields/Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URL__c</fullName>
    <label>Redirect URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Twitter_Setting__mdt/fields/Upload_Media_API_URL__c.field-meta.xml
<CustomField>
    <fullName>Upload_Media_API_URL__c</fullName>
    <label>Upload Media API URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TwitterMetadataSelector.cls
public class TwitterMetadataSelector {
    
    private static final String TWITTER_SETTING_API_NAME = 'Twitter_Setting';
    
    public static List<Twitter_Setting__mdt> getTwitterSettingMetadata() {
        return [SELECT Id 
                , Base_API_URL__c
                , Upload_Media_API_URL__c
                , Consumer_Key__c
                , Consumer_Secret__c
                , Client_Id__c
                , Client_Secret__c
                , Code_Challenge__c
                , Redirect_Url__c
                , Access_Token__c
                , Access_Token_Secret__c
                FROM Twitter_Setting__mdt 
                WHERE DeveloperName = : TWITTER_SETTING_API_NAME
               ];
    }
    
    
}