force-app/main/default/objects/Contact/fields/Twitter_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Twitter_Access_Token__c</fullName>
    <label>Twitter Access Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tweet__c/Tweet__c.object-meta.xml
<CustomObject>
    <label>Tweet</label>
    <nameField>
        <label>Tweet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tweets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tweet__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tweets</relationshipLabel>
    <relationshipName>Tweets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/Tweet_Date__c.field-meta.xml
<CustomField>
    <fullName>Tweet_Date__c</fullName>
    <label>Tweet Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/Tweet_ID__c.field-meta.xml
<CustomField>
    <fullName>Tweet_ID__c</fullName>
    <label>Tweet ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/Tweet_Text__c.field-meta.xml
<CustomField>
    <fullName>Tweet_Text__c</fullName>
    <label>Tweet Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RecentTweetsController.cls
public class RecentTweetsController {
    
    @AuraEnabled
    public static Integer getTweetCount(Id contactId) {
        return [SELECT COUNT() FROM Tweet__c WHERE Contact__c = :contactId];
    }
    
    @AuraEnabled
    public static List<Tweet__c> getTweets(Id contactId, Integer pageNumber, Integer pageSize) {
        Integer offset = (pageNumber - 1) * pageSize;
        return [
            SELECT Id
            , Tweet_Text__c
            , Tweet_Date__c
            , Tweet_Id__c
            FROM Tweet__c 
            WHERE Contact__c = :contactId 
            ORDER BY Tweet_Date__c DESC
            LIMIT :pageSize OFFSET :offset
        ];
    }
    
    @AuraEnabled
    public static AuraResponse deleteTweet(String tweetId) {
        Logger logger = Logger.getInstance();
        Tweet__c tweet = [SELECT Id, Tweet_Id__c, Contact__r.Twitter_Access_Token__c FROM Tweet__c WHERE Tweet_Id__c = :tweetId LIMIT 1];
        TwitterCalloutService calloutService = new TwitterCalloutService();
        
        TwitterWrappers.DeleteTweetResponse deleteTweetWrapper = calloutService.deleteTweet(tweetId, tweet.Contact__r.Twitter_Access_Token__c);
        
        try{
            if (deleteTweetWrapper.data.deleted) {
                delete tweet;
                return new AuraResponse(true, deleteTweetWrapper, 'Success');
            }else{
                return new AuraResponse(false, deleteTweetWrapper.errorResponseObj, 'Failed');
            }
        }catch(Exception ex){
            logger.error(null, null, 'RecentTweetsController', 'deleteTweet', ex.getMessage());
            logger.publish();
            return new AuraResponse(false, ex.getMessage());
        }
    }
    
}